#!/bin/bash

mqtt publish -t 'version/2.27/' -h 'saturten.com' -p 8883 -C 'mqtts' -m 'yo' -u 'andrew' -P '1plus2is3'
mqtt publish -t 'version/2.24/' -h 'saturten.com' -p 8883 -C 'mqtts' -m 'yo' -u 'andrew' -P '1plus2is3'
mqtt publish -t 'version/2.20/' -h 'saturten.com' -p 8883 -C 'mqtts' -m 'yo' -u 'andrew' -P '1plus2is3'
mqtt publish -t 'version/2.28/' -h 'saturten.com' -p 8883 -C 'mqtts' -m 'yo' -u 'andrew' -P '1plus2is3'
mqtt publish -t 'version/2.18/' -h 'saturten.com' -p 8883 -C 'mqtts' -m 'yo' -u 'andrew' -P '1plus2is3'
mqtt publish -t 'version/2.19/' -h 'saturten.com' -p 8883 -C 'mqtts' -m 'yo' -u 'andrew' -P '1plus2is3'
mqtt publish -t 'version/2.21/' -h 'saturten.com' -p 8883 -C 'mqtts' -m 'yo' -u 'andrew' -P '1plus2is3'
mqtt publish -t 'version/2.29/' -h 'saturten.com' -p 8883 -C 'mqtts' -m 'yo' -u 'andrew' -P '1plus2is3'
mqtt publish -t 'version/2.15/' -h 'saturten.com' -p 8883 -C 'mqtts' -m 'yo' -u 'andrew' -P '1plus2is3'
mqtt publish -t 'version/2.17/' -h 'saturten.com' -p 8883 -C 'mqtts' -m 'yo' -u 'andrew' -P '1plus2is3'
mqtt publish -t 'version/2.16/' -h 'saturten.com' -p 8883 -C 'mqtts' -m 'yo' -u 'andrew' -P '1plus2is3'
mqtt publish -t 'version/2.30/' -h 'saturten.com' -p 8883 -C 'mqtts' -m 'yo' -u 'andrew' -P '1plus2is3'
mqtt publish -t 'version/2.23/' -h 'saturten.com' -p 8883 -C 'mqtts' -m 'yo' -u 'andrew' -P '1plus2is3'
mqtt publish -t 'version/2.22/' -h 'saturten.com' -p 8883 -C 'mqtts' -m 'yo' -u 'andrew' -P '1plus2is3'
mqtt publish -t 'version/2.25/' -h 'saturten.com' -p 8883 -C 'mqtts' -m 'yo' -u 'andrew' -P '1plus2is3'
mqtt publish -t 'version/3.30/' -h 'saturten.com' -p 8883 -C 'mqtts' -m 'yo' -u 'andrew' -P '1plus2is3'
mqtt publish -t 'version/3.31/' -h 'saturten.com' -p 8883 -C 'mqtts' -m 'yo' -u 'andrew' -P '1plus2is3'
